-- =====================================================================
-- restaurant_settings was a hard singleton (id fixed at 1 by a CHECK
-- constraint). Onboarding a new restaurant needs a second settings row,
-- so id becomes a normal generated key; restaurant_id (unique, added in
-- V4) is what identifies "this restaurant's settings row" now.
-- =====================================================================

ALTER TABLE restaurant_settings DROP CONSTRAINT restaurant_settings_id_check;

ALTER TABLE restaurant_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
